import React from "react";
import type { GRAPStatusResponse } from "../types";
import { CheckCircle2, AlertTriangle, AlertOctagon, FileDown } from "lucide-react";

interface GRAPAdvisorViewProps {
  grap: GRAPStatusResponse | null;
}

export const GRAPAdvisorView: React.FC<GRAPAdvisorViewProps> = ({ grap }) => {
  if (!grap) return null;

  const getStageHeaderColor = (stage: string, active: boolean) => {
    if (!active) return "bg-slate-900/60 border-slate-800 text-slate-400";
    if (stage.includes("Stage IV")) return "bg-red-950/80 border-red-600 text-red-300 shadow-lg shadow-red-900/30";
    if (stage.includes("Stage III")) return "bg-purple-950/80 border-purple-600 text-purple-300 shadow-lg shadow-purple-900/30";
    if (stage.includes("Stage II")) return "bg-rose-950/80 border-rose-600 text-rose-300 shadow-lg shadow-rose-900/30";
    return "bg-amber-950/80 border-amber-600 text-amber-300 shadow-lg shadow-amber-900/30";
  };

  const exportReport = () => {
    const reportText = `=====================================================
CAQM GRADED RESPONSE ACTION PLAN (GRAP) FORECAST ADVISORY
Generated by DELHI-AIR-COUPLED System
=====================================================
Active Status: ${grap.current_stage}
72-Hour Max Projected AQI: ${grap.max_forecast_aqi}
Critical Inversion Window: ${grap.critical_time_window}
Primary Episode Driver: ${grap.primary_driver}

-----------------------------------------------------
STATUTORY ENFORCEMENT ACTIONS BY STAGE:
${grap.stages.map(s => `
[${s.stage}: ${s.title}] - ${s.active ? "ACTIVATED" : "INACTIVE"}
Threshold: ${s.aqi_range}
Key Interventions:
${s.key_actions.map(a => `  • ${a}`).join("\n")}
Public Guidelines:
${s.public_health_guidelines.map(g => `  - ${g}`).join("\n")}
`).join("\n")}
=====================================================`;

    const blob = new Blob([reportText], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `GRAP_Advisory_Report_${new Date().toISOString().slice(0,10)}.txt`;
    link.click();
  };

  return (
    <div className="space-y-4">
      {/* Active Stage Alert Hero */}
      <div className="p-5 rounded-2xl glass-panel border border-red-600/40 bg-gradient-to-r from-red-950/50 via-slate-900/80 to-purple-950/40 shadow-2xl">
        <div className="flex flex-col lg:flex-row items-start lg:items-center justify-between gap-4">
          <div className="flex items-start gap-3">
            <div className="p-3 rounded-xl bg-red-600/20 text-red-400 border border-red-500/40 animate-pulse">
              <AlertOctagon className="w-6 h-6" />
            </div>
            <div>
              <div className="flex items-center gap-2">
                <span className="text-xs uppercase tracking-wider font-bold text-red-400">
                  Statutory CAQM Directive Active
                </span>
                <span className="px-2 py-0.5 rounded bg-red-900/80 text-red-200 text-xs font-black">
                  {grap.current_stage}
                </span>
              </div>
              <h2 className="text-xl font-black text-white mt-1">
                Emergency Inversion & Pollution Protocol Triggered
              </h2>
              <p className="text-xs text-slate-300 mt-1 max-w-2xl">
                {grap.primary_driver}. Peak 72h AQI projected at <b>{grap.max_forecast_aqi}</b>.
              </p>
            </div>
          </div>

          <button
            onClick={exportReport}
            className="flex items-center gap-2 px-4 py-2.5 rounded-xl bg-slate-800/90 hover:bg-slate-700 text-white text-xs font-bold border border-slate-700 shadow-md transition active:scale-95"
          >
            <FileDown className="w-4 h-4 text-cyan-400" />
            <span>Export Official GRAP Brief</span>
          </button>
        </div>
      </div>

      {/* 4-Stage Breakdown Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        {grap.stages.map((stg) => {
          const isActivated = stg.active;
          return (
            <div
              key={stg.stage}
              className={`p-5 rounded-2xl border transition-all ${getStageHeaderColor(stg.stage, isActivated)}`}
            >
              <div className="flex items-center justify-between border-b border-slate-800/80 pb-3 mb-3">
                <div>
                  <div className="flex items-center gap-2">
                    <span className="font-black text-sm">{stg.stage}</span>
                    <span className="text-xs opacity-75 font-semibold">({stg.aqi_range})</span>
                  </div>
                  <h4 className="font-bold text-white text-sm mt-0.5">{stg.title}</h4>
                </div>
                <span className={`px-2.5 py-1 rounded-lg text-xs font-bold flex items-center gap-1 ${
                  isActivated ? "bg-red-500/20 text-red-300 border border-red-500/40" : "bg-slate-800 text-slate-500"
                }`}>
                  {isActivated ? <AlertTriangle className="w-3 h-3" /> : <CheckCircle2 className="w-3 h-3" />}
                  {isActivated ? "ENFORCED" : "STANDBY"}
                </span>
              </div>

              {/* Key Mandated Actions */}
              <div className="space-y-3">
                <div>
                  <span className="text-[11px] uppercase tracking-wider font-bold text-slate-300 block mb-1.5">
                    Mandatory Municipal Enforcement:
                  </span>
                  <ul className="space-y-1.5 text-xs text-slate-300">
                    {stg.key_actions.map((act, idx) => (
                      <li key={idx} className="flex items-start gap-2">
                        <span className="text-cyan-400 font-bold">•</span>
                        <span>{act}</span>
                      </li>
                    ))}
                  </ul>
                </div>

                <div className="pt-2 border-t border-slate-800/60">
                  <span className="text-[11px] uppercase tracking-wider font-bold text-amber-400 block mb-1.5">
                    Public Health Advisory:
                  </span>
                  <ul className="space-y-1 text-[11px] text-slate-300">
                    {stg.public_health_guidelines.map((g, idx) => (
                      <li key={idx} className="flex items-start gap-1.5">
                        <span className="text-amber-400">-</span>
                        <span>{g}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
};
