'use client'

import { CircleCheck, Download, HeartPulse, ShieldAlert } from 'lucide-react'
import { cn } from '@/lib/utils'
import type { HourlyForecastPoint } from '@/lib/types'
import { GRAP_STAGES, formatIST, grapFromAqi } from '@/lib/aqi'
import { Explainer, Panel } from './primitives'

const ACTIONS: Record<string, { enforcement: string[]; health: string[] }> = {
  I: {
    enforcement: [
      'Stop C&D on unregistered plots above 500 m²',
      'Mechanised road sweeping & water sprinkling',
      'Strict PUC checks; fine visibly polluting vehicles',
      'Ban open burning of waste and biomass',
    ],
    health: ['Sensitive groups limit prolonged outdoor exertion', 'Keep rescue medication handy'],
  },
  II: {
    enforcement: [
      'Ban diesel generators except emergency services',
      'Raise parking fees to discourage private cars',
      'Increase CNG / electric bus & Metro frequency',
      'Daily dust suppression at hotspots',
    ],
    health: ['Everyone avoid long outdoor exercise', 'Use N95 masks near traffic corridors'],
  },
  III: {
    enforcement: [
      'Ban non-essential construction & demolition',
      'Ban BS-III petrol & BS-IV diesel cars in NCR',
      'Shut stone crushers and mining',
      'Primary classes shift to hybrid mode',
    ],
    health: ['Avoid all outdoor physical activity', 'Children and elderly stay indoors'],
  },
  IV: {
    enforcement: [
      'Stop truck entry except essential, CNG or EV',
      'Halt all C&D including public linear projects',
      '50% work-from-home for public & private offices',
      'Schools may move classes online',
    ],
    health: ['Public health emergency — stay indoors', 'Run air purifiers; seal windows & doors'],
  },
}

export function GrapView({ point }: { point: HourlyForecastPoint }) {
  const active = grapFromAqi(point.aqi)
  const activeIdx = GRAP_STAGES.findIndex((s) => s.id === active.id)

  const exportBrief = () => {
    const stages = GRAP_STAGES.slice(0, activeIdx + 1)
    const lines = [
      'COMMISSION FOR AIR QUALITY MANAGEMENT — GRAP BRIEF',
      'Generated by DELHI-AIR-COUPLED (WRF-Chem v4.5+ emulated)',
      '='.repeat(60),
      `Valid time: ${formatIST(point.timestamp)} IST`,
      `Forecast AQI: ${point.aqi} (${point.aqi_category})  |  PM2.5: ${point.pm25} µg/m³`,
      `Active stage: ${active.name} — ${active.short}`,
      `Drivers: PBL ${point.pbl_height_m} m, wind ${point.wind_speed_kmh} km/h ${point.wind_dir_compass}, stubble share ${point.stubble_contribution_pct}%`,
      '',
      ...stages.flatMap((s) => [
        `${s.name.toUpperCase()} (${s.range}) — cumulative actions:`,
        ...ACTIONS[s.id].enforcement.map((a) => `  • ${a}`),
        '  Health advisory:',
        ...ACTIONS[s.id].health.map((a) => `  • ${a}`),
        '',
      ]),
    ]
    const blob = new Blob([lines.join('\n')], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `GRAP-brief-${point.timestamp.slice(0, 13)}.txt`
    a.click()
    URL.revokeObjectURL(url)
  }

  return (
    <div className="grid gap-4">
      <Panel glow className="relative overflow-hidden">
        <div className="pointer-events-none absolute -right-20 -top-20 size-72 rounded-full opacity-25 blur-3xl" style={{ backgroundColor: active.color }} />
        <div className="relative flex flex-wrap items-center justify-between gap-4">
          <div className="flex items-center gap-4">
            <div className="flex size-16 items-center justify-center rounded-2xl" style={{ backgroundColor: `${active.color}22`, color: active.color }}>
              <ShieldAlert className="size-8" aria-hidden />
            </div>
            <div>
              <p className="text-xs font-semibold uppercase tracking-[0.16em] text-muted-foreground">CAQM Graded Response Action Plan</p>
              <h2 className="text-2xl font-extrabold" style={{ color: active.color }}>
                {active.name} · {active.short}
              </h2>
              <p className="mt-1 max-w-xl text-sm text-slate-300">
                Forecast AQI <strong className="font-mono">{point.aqi}</strong> at {formatIST(point.timestamp)} IST, driven by a{' '}
                {point.pbl_height_m < 500 ? 'shallow mixing layer' : 'moderate mixing layer'}, {point.wind_speed_kmh} km/h winds and{' '}
                {point.stubble_contribution_pct}% stubble smoke.
              </p>
            </div>
          </div>
          <button onClick={exportBrief} className="flex items-center gap-2 rounded-full bg-foreground px-4 py-2.5 text-sm font-semibold text-background transition hover:opacity-90">
            <Download className="size-4" aria-hidden /> Export official brief
          </button>
        </div>

        <div className="relative mt-6 flex gap-1" aria-hidden>
          {GRAP_STAGES.map((s, i) => (
            <div key={s.id} className="flex-1">
              <div className="h-2 rounded-full" style={{ backgroundColor: i <= activeIdx ? s.color : 'rgba(255,255,255,0.08)' }} />
              <p className="mt-1.5 text-[11px] text-muted-foreground">{s.range}</p>
            </div>
          ))}
        </div>
      </Panel>

      <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4">
        {GRAP_STAGES.map((s, i) => {
          const on = i <= activeIdx
          return (
            <article
              key={s.id}
              className={cn('glass flex flex-col rounded-2xl p-4 transition', !on && 'opacity-55')}
              style={on ? { boxShadow: `inset 0 0 0 1px ${s.color}55, 0 0 30px -12px ${s.color}` } : undefined}
            >
              <div className="flex items-center justify-between">
                <h3 className="font-bold" style={{ color: s.color }}>
                  {s.name}
                </h3>
                <span
                  className="rounded-full px-2 py-0.5 text-[11px] font-semibold"
                  style={on ? { backgroundColor: `${s.color}22`, color: s.color } : { backgroundColor: 'rgba(255,255,255,0.06)', color: '#94a3b8' }}
                >
                  {on ? 'In force' : 'Standby'}
                </span>
              </div>
              <p className="text-xs text-muted-foreground">
                {s.short} · {s.range}
              </p>
              <ul className="mt-3 flex flex-col gap-2 text-sm">
                {ACTIONS[s.id].enforcement.map((a) => (
                  <li key={a} className="flex gap-2">
                    <CircleCheck className="mt-0.5 size-4 shrink-0" style={{ color: on ? s.color : '#475569' }} aria-hidden />
                    <span className="text-slate-300">{a}</span>
                  </li>
                ))}
              </ul>
              <div className="mt-auto pt-4">
                <div className="rounded-xl bg-white/[0.03] p-3">
                  <p className="flex items-center gap-1.5 text-xs font-semibold text-rose">
                    <HeartPulse className="size-3.5" aria-hidden /> Health advisory
                  </p>
                  <ul className="mt-1 text-xs text-slate-300">
                    {ACTIONS[s.id].health.map((h) => (
                      <li key={h}>{h}</li>
                    ))}
                  </ul>
                </div>
              </div>
            </article>
          )
        })}
      </div>

      <Explainer>
        GRAP is Delhi-NCR&apos;s emergency rulebook. Stages are <strong className="text-foreground">cumulative</strong>: when Stage III is triggered,
        all Stage I and II rules also apply. This forecast lets authorities switch stages on <em>before</em> the air gets that bad.
      </Explainer>
    </div>
  )
}
